services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "Quem me deve"
      APP_ENV: local
      APP_KEY: base64:Izy+tdr6e2uVEeUZzcGL6v12FYg3j0QMPUuBsDDFS5g=
      APP_DEBUG: "true"
      APP_TIMEZONE: America/Sao_Paulo
      APP_URL: http://localhost:8000
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_DATABASE: quem
      DB_USERNAME: quem
      DB_PASSWORD: secret
      SESSION_DRIVER: database
      CACHE_STORE: database
      QUEUE_CONNECTION: database
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-time-zone=-03:00 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: quem
      MYSQL_USER: quem
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
